---
title: "Lab10_James"
author: "James Forster III"
date: "2024-03-27"
output: 
  html_document:
    toc: true
    toc_depth: 5
    theme: cerulean 
    highlight: monochrome
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
library(readr)
```

```{r}
Project_MAGs <- read.csv("Project_MAGs.csv") 
```

```{r}
Project_MAGs_LBJ <- Project_MAGs %>% 
  filter(Site == "National Grasslands LBJ, Texas, USA")
```

## National Grasslands LBJ MAGs Overview 


```{r, fig.width = 9, fig.height = 5}
Project_MAGs_LBJ %>% 
ggplot(aes(x = fct_rev(fct_infreq(Phylum)))) +
    geom_bar(color = "cyan") +
    labs(title = "Phylum Counts for MAGs at National Grasslands LBJ, Texas, USA", x = "Phylum", y = "Number of MAGs") +
theme(axis.text.x = element_text(size = 15, angle = 0, hjust = 1, vjust = 1),
                        axis.text.y = element_text(size = 15),
                        text = element_text(size = 15), plot.title = element_text(size = 17, hjust = 2))+
  coord_flip() 
```

```{r, fig.width = 9, fig.height = 5}
Project_MAGs_LBJ %>% 
ggplot(aes(x = fct_rev(fct_infreq(Class)))) +
    geom_bar(color = "cyan") +
    labs(title = "Class Counts for MAGs at National Grasslands LBJ, Texas, USA", x = "Class", y = "Number of MAGs") +
theme(axis.text.x = element_text(size = 15, angle = 0, hjust = 1, vjust = 1),
                        axis.text.y = element_text(size = 12),
                        text = element_text(size = 15), plot.title = element_text(size = 17, hjust = -2))+
  coord_flip() 
```

```{r}
Project_MAGs_LBJ %>% 
ggplot(aes(x= Total.Number.of.Bases)) +
  labs(title = "Genome Size Analysis for MAGs at National Grasslands LBJ, Texas, USA", x = "Total Number of Bases", y = "Number of MAGs") +
  geom_histogram(bins = 20, color = "cyan") +
  scale_x_continuous(breaks = seq(0, max(Project_MAGs_LBJ$Total.Number.of.Bases), by = 1000000)) +
  theme(axis.text.x = element_text(size = 15, angle = 45, hjust = 1, vjust = 1),
                        axis.text.y = element_text(size = 12),
                        text = element_text(size = 15), plot.title = element_text(size = 15, hjust = 1))


```


```{r}
datatable(Project_MAGs_LBJ)
```



```{r}
Site_IMG <- read_tsv("data/exported_img_data.tsv")  #Loading TSV of IMG data for LBJ site
datatable(Site_IMG)
```


